### ISSUE TITLE
Using a CSS Dropdown with 52framework

### ISSUE THREAD

**Issue by teknix** [agrublev/52framework#1]
Hello,

First of, great work! It has drastically reduced my design time!

But i do have a question. I have attempted to use jquery and straight CSS3 dropdown menu's to work ( http://net.tutsplus.com/tutorials/html-css-techniques/how-to-create-a-drop-down-nav-menu-with-html5-css3-and-jquery/ ) with absolutely no luck. :(

Could some one maybe point me in the right direction? Something that was successful for them?

thank you VERY much for your time

**Comment by agrublev** [comment]
I would be very concerned that your javascript and css have an issue and it has nothing to do with the framework itself. I have implemented many dropdown solutions with 52framework as backend... so please follow their steps and post within that blog post to get help.
